---
- name: start | stop | restart apache2
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Starting apache2 server 
      systemd:
        name: apache2
        enabled: yes
        masked: no
    - name: Status apache2 server
      systemd:
        name: apache2
        state: started
    - name: Stopping apache2 server 
      systemd:
        name: apache2
        state: stopped
    - name: Status apache2 server
      systemd:
        state: stopped
        name: apache2
    - name: Restarting apache2 server 
      systemd:
        name: apache2
        enabled: yes
        masked: no
    - name: Status apache2 server
      systemd:
        state: started
        name: apache2


